### ISSUE TITLE
Add explanation of labels to either CONTRIBUTING.md or separate core/HOWTO.md

### ISSUE THREAD

**Issue by drllau** [zinc-collective/compensated#56]
_Originally posted by @zspencer in https://github.com/zinc-collective/compensated/issues/50#issuecomment-605694538_
> Issues labeled "enhancement" are the "inner loop" of a [double-loop learning system](https://en.wikipedia.org/wiki/Double-loop_learning). They exist to take the higher-order design considerations and turn them into changes to the underlying documentation,  designs, or code. Issues labeled "request for comment" are for the outer-loop.
>
> This ensures people who want to focus on "what to build" don't have to wade through long conversations to get to the mockups/use cases/acceptance tests; and ensures that people who want the broad, overarching philosophy can have those conversations as well.

1. Someone to document the various labels that have been setup and what that means when contributing. 
2. Double bonus, work out a competency level which allows one to practice using the labels, in line with a [badgebot](https://github.com/bocoup/bots/wiki/Badgebot)
3. For a real DesignNinga, write a compensated bot that affirms the Coop's values of a warm neighbourhood and Code of Conduct.

**Comment by user512** [comment]
Closing since labels meaning is documented and open for feedback if it wasn't clear.
